spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_shiro?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.xej.pojo
  configuration:
    map-underscore-to-camel-case: true   # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性


#shiro:
#  login-url: /welcome
#  unauthorized-url: /unauthorized
#  anon-urls:
#    - /user/toLogin